document.writeln("<script type=\"text/javascript\">			");
document.writeln("	function check() {");
document.writeln("		if (gh_form.name.value==\"\"){alert(\"请填入您的姓名\");gh_form.name.focus();return false}");
document.writeln("		if (gh_form.tel.value==\"\"){alert(\"请填入您的联系方式\");gh_form.tel.focus();return false}");
document.writeln("		/*if(!gh_form.tel.value.match(/^^\/\/d{11}$/)) {");
document.writeln("		alert(\'手机号码输入有误\');return false;");
document.writeln("		gh_form.tel.focus();return false");
document.writeln("	}*/ 	");
document.writeln("		if (gh_form.yydate.value==\"\"){alert(\"请填入您的就诊日期\");gh_form.yydate.focus();return false}");
document.writeln("		");
document.writeln("		return true;");
document.writeln("	}");
document.writeln("	//过滤空格");
document.writeln("	function ignoreSpaces(string) {");
document.writeln("		var temp = \"\";");
document.writeln("		string = \'\' + string;");
document.writeln("		splitstring = string.split(\" \");");
document.writeln("		for(i = 0; i < splitstring.length; i++)");
document.writeln("		temp += splitstring[i];");
document.writeln("		return temp;");
document.writeln("	}");
document.writeln("	</script>");
document.writeln("<div class=\"from\">");
document.writeln("<h2 class=\"title\">已知病情  在线挂号</h2>");
document.writeln("<p class=\"point\">（本站已加密，绝对保障个人隐私）</p>");
document.writeln("");
document.writeln("");
document.writeln("<form id=\"gh_form\" name=\"gh_form\" onsubmit=\"javascript:return check();\" target=\"_blank\" autocomplete=\"off\" method=\"post\" action=\"/sysplus/guahao.php?act=add\">");
document.writeln("");
document.writeln("<table width=\"80%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td width=\"29%\" align=\"center\"><span>患者姓名 :</span></td>");
document.writeln("    <td width=\"71%\"><input type=\"text\" class=\"tet01\" id=\"name\" name=\"name\" onblur=\"this.value=ignoreSpaces(this.value);\" /></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><span>联系方式 :</span></td>");
document.writeln("    <td><input type=\"text\" class=\"tet01\" id=\"contacts\" name=\"tel\" onblur=\"this.value=ignoreSpaces(this.value);\" /></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><span>就诊日期 :</span></td>");
document.writeln("    <td><input class=\"Wdate\" type=\"text\" onClick=\"WdatePicker()\" /></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><span>主诉症状 :</span></td>");
document.writeln("    <td><input type=\"text\" /></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><span>预约专家 :</span></td>");
document.writeln("    <td><select name=\"doctor\">");
document.writeln("                    <option value=\"沈启刚\">沈启刚</option>");
document.writeln("                    <option value=\"许莉莉\">许莉莉</option>");
document.writeln("");
document.writeln("                    ");
document.writeln("                </select></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"2\">");
document.writeln("     <table width=\"90%\" border=\"0\">");
document.writeln("   <tr>");
document.writeln("    <td><input class=\"bt\" type=\"submit\" value=\"提交挂号\" onClick=\"return check();\"></td>");
document.writeln("    <td><a class=\"rf\" onclick=\"LR_HideInvite();openZoosUrl();return false;\" href=\"javascript:void(0)\">咨询专家</a></td>");
document.writeln("  </tr>");
document.writeln("</table>");
document.writeln("</td>");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("</form>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\"foot_nav cen\"><a href=\"/\">医院首页</a> |  <a href=\"/js/\">医院介绍</a> |  <a href=\"/zjtd/\">专家团队</a> |  <a href=\"/qwlf/\">特色疗法</a></div>");
document.writeln("<footer>");
document.writeln("<img src=\"./images/foot1.png\" />");
document.writeln("<p class=\"cen\">接诊时间：8：00~17:00   <br/>");
document.writeln("医院地址：天津市河西区黑牛城道189号<br/>");
document.writeln("（紫金山路交口，大润发超市斜对面）");
document.writeln("</p>");
document.writeln("</footer>");
document.writeln("");
document.writeln("<!--box end-->");
